//
//  ProductListWorkerTests.swift
//  CicekSepetiCaseApp
//
//  Created by KS Murat Turan on 18.07.2019.
//  Copyright (c) 2019 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CicekSepetiCaseApp
import XCTest

class ProductListWorkerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ProductListWorker!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupProductListWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupProductListWorker()
  {
    sut = ProductListWorker()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testFetchProducts() {
    let expectation = self.expectation(description: "Wait for fetchProducts() to return.")
    sut.fetchProductList(success: { (ProductBaseModel) in
        expectation.fulfill()
        XCTAssert(true)
    }) { (error) in
        expectation.fulfill()
        XCTAssert(false)
    }
    waitForExpectations(timeout: 60)
  }
}
